apiVersion: apps/v1
kind: Deployment #這是一個 Deployment，用於管理多個相同的 Pod 副本。
metadata:
  name: flask-library
spec:
  replicas: 1  # 定義 1 個副本，Kubernetes 會管理這些 Pod
  selector:
    matchLabels:
      app: flask-library #確保 Deployment 只管理 app: flask-library 的 Pod，與 flask-service.yaml 內的 selector 相匹配。
  template:
    metadata:
      labels:
        app: flask-library #設置 Pod 的 label，以便 Service 可以找到這些 Pod。
    spec:
      containers:
      - name: flask-library
        image: flask-app-mysql:latest  # 你的 Flask 應用 Docker 映像
        ports:
        - containerPort: 5010
        env:
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "mysql"
        - name: DB_HOST
          value: "mysql"
        - name: DB_NAME
          value: "mydb"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-library
spec:
  selector:
    app: flask-library
  ports:
  - port: 80
    targetPort: 5010
  type: LoadBalancer