apiVersion: v1
kind: Service
metadata:
  name: myapp-flask-book-app
spec:
  selector:
    app: flask-book-app
  ports:
    - protocol: TCP
      port: 5010      # Kubernetes 內部 Port
      targetPort: 5010 # 容器內部 Port
      nodePort: 30510  # 外部訪問的 Port
  type: NodePort